# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION='v.2.0.0'
            BODY_CONTENT='This is demo content'
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -b ${BODY_CONTENT} -delete ${VERSION} ./

workflows:
  version: 2
  release:
    jobs:
      - publish-github-release:
          context: org-global
          filters:
            branches:
              only:
                - master
            tags:
              only: /^\d+\.\d+\.\d+$/

