# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  publish-github-release:
    working_directory: ~/demo_versioning
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION='v.2.0.0'
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -b 'This is demo content' -delete ${VERSION} ~/.

workflows:
  version: 2
  release:
    jobs:
      - publish-github-release:
          context: org-global
