# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  publish-github-release:
    working_directory: ~/app
    docker:
      #- image: cibuilds/github:0.10
      - image: dieunb/release_testing:0.0.3
    steps:
      - checkout
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION="$(node /usr/src/app/version.js -f ~/app/app.json)"
            RELEASE_NOTE="$(node /usr/src/app/release_note.js -f ~/app/CHANGELOG.md -v $VERSION)"
            ~/go/bin/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -b "${RELEASE_NOTE}" -delete ${VERSION} ./

workflows:
  version: 2
  release:
    jobs:
      - publish-github-release:
          context: org-global
