# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  publish-github-release:
    working_directory: ~/app
    docker:
      #- image: cibuilds/github:0.10
      - image: ehdevops/release_lib:0.0.1
        environment:
          GITHUB_REPOSITORY: 'ehdieunguyen/release_validation'
    steps:
      - checkout
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(echo `cat ~/app/app.json` | jq .version | tr -d \")
            RELEASE_NOTE=$(node /usr/src/app/release_note.js -f ~/app/CHANGELOG.md -v $VERSION)
            echo "${RELEASE_NOTE}" > /release/release_note.txt
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -b "${RELEASE_NOTE}" -delete ${VERSION} /release/

workflows:
  version: 2
  release:
    jobs:
      - publish-github-release:
          context: org-global
